apiVersion: v1
kind: Service
metadata:
  name: golang-app-service
spec:
  selector:
    app: golang-app  # Must match the labels in deployment.yaml
  ports:
    - protocol: TCP
      port: 80        # External port for accessing service
      targetPort: 8080 # The port inside the container
  type: LoadBalancer  # Exposes the service externally
